language: ruby
rvm:
  - 1.9.3
  - 2.1.1
services:
  - redis-server
script: bundle exec rspec
notifications:
  hipchat:
    rooms:
      secure: JeNdLh43NL9hlzRwAm9T5rjpjpJdI/cH6Er05advfT+9BTPI09U3OcDVkxlsBU5KCkItHVZcIjcRMAxDspqQ7od7a2bjUjOMTg8qZHhZPDUeXCWRCBvhAjuecvQycPekY5OUDpHlg5S5GLZ3d9W5khB4xwDQrkKoHvhp09WxfvU=
    template:
    - ! '%{author}''s %{repository}/%{branch} - <a href="%{build_url}">%{message}</a>'
    format: html
